@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json
Accept: application/json

{
    "firstName": "Julia",
    "lastName": "Berrebi"
}

###
GET {{base_address}}

###
GET {{base_address}}/3

###
PUT {{base_address}}/3
Content-Type: application/json
Accept: application/json

{
    "personId": 3,
    "firstName": "Peach",
    "lastName": "Berrebi"
}
