@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json
Accept: application/json

{
    "firstName": "Victor",
    "lastName": "Recabarren"
}

###
GET {{base_address}}

###
GET {{base_address}}/4

###
PUT {{base_address}}/4
Content-Type: application/json
Accept: application/json

{
    "personId": 4,
    "firstName": "Victor",
    "lastName": "MR"
}

###
DELETE  {{base_address}}/4